apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.APP_ID}}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: helm
    repoURL: https://github.com/vfarcic/devops-toolkit.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: vfarcic/devops-toolkit
          tag: {{.IMAGE_TAG}}
        ingress:
          host: {{.APP_ID}}.devopstoolkitseries.com
      version: v3
  destination:
    namespace: "{{.APP_ID}}"
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
