apiVersion: v1
kind: Pod
metadata:
  name: "hackathon-test"
  annotations:
    "helm.sh/hook": test-success
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  containers:
    - name: hackathon-test
      image: python:3.7-slim-buster
      imagePullPolicy: IfNotPresent
      command:
        - /bin/bash
        - -ec
        - |
                    echo "Tests are successful!"
  restartPolicy: Never
