apiVersion: v1
kind: Pod
metadata:
  name: "hackathon-test"
  annotations:
    "helm.sh/hook": test
spec:
  imagePullSecrets:
  - name: regcred
  containers:
    - name: hackathon-test
      image: python:3.7-slim-buster
      imagePullPolicy: IfNotPresent
      command:
        - /bin/bash
        - -ec
        - |
                    bash -c min=$(date +"%M");rem=$(( min % 2 ));echo $( date );if [ "$rem" == "1" ]; then echo "Some Tests have failed...";exit 1; else echo "All tests have passed..."; fi
  restartPolicy: Never
